ALTER TABLE transactions
  ADD COLUMN IF NOT EXISTS source_upload_id BIGINT REFERENCES transaction_uploads(id),
  ADD COLUMN IF NOT EXISTS source_type TEXT,
  ADD COLUMN IF NOT EXISTS source_raw_json JSONB,
  ADD COLUMN IF NOT EXISTS driver_name TEXT,
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS province TEXT,
  ADD COLUMN IF NOT EXISTS computed_rate_per_liter NUMERIC,
  ADD COLUMN IF NOT EXISTS markup_per_liter NUMERIC,
  ADD COLUMN IF NOT EXISTS subtotal NUMERIC,
  ADD COLUMN IF NOT EXISTS gst NUMERIC,
  ADD COLUMN IF NOT EXISTS pst NUMERIC,
  ADD COLUMN IF NOT EXISTS qst NUMERIC,
  ADD COLUMN IF NOT EXISTS total NUMERIC;
