-- Add computed tax fields to transactions
ALTER TABLE transactions
  ADD COLUMN IF NOT EXISTS province VARCHAR(10),
  ADD COLUMN IF NOT EXISTS computed_rate_per_liter NUMERIC(10,4),
  ADD COLUMN IF NOT EXISTS subtotal NUMERIC(12,4),
  ADD COLUMN IF NOT EXISTS gst NUMERIC(12,4),
  ADD COLUMN IF NOT EXISTS pst NUMERIC(12,4),
  ADD COLUMN IF NOT EXISTS qst NUMERIC(12,4),
  ADD COLUMN IF NOT EXISTS total NUMERIC(12,4);
