ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS customer_number VARCHAR(20) UNIQUE,
  ADD COLUMN IF NOT EXISTS owner_name VARCHAR(150),
  ADD COLUMN IF NOT EXISTS city VARCHAR(100),
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS bv TEXT,
  ADD COLUMN IF NOT EXISTS fuellink_card INTEGER,
  ADD COLUMN IF NOT EXISTS otp_setup TEXT,
  ADD COLUMN IF NOT EXISTS deposit NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS security_deposit_invoice TEXT,
  ADD COLUMN IF NOT EXISTS customer_status BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS reference_name TEXT,
  ADD COLUMN IF NOT EXISTS comment TEXT;
